import { Router } from 'express';
import authRoutes from './authRoutes';
import courseRoutes from './courseRoutes';
import enrollmentRoutes from './enrollmentRoutes';
import materialRoutes from './materialRoutes';
import quizRoutes from './quizRoutes';
import userRoutes from './userRoutes';
import notificationRoutes from './notificationRoutes';
import uploadRoutes from './uploadRoutes';
const router = Router();
router.use('/auth', authRoutes);
router.use('/courses', courseRoutes);
router.use('/enrollments', enrollmentRoutes);
router.use('/materials', materialRoutes);
router.use('/quizzes', quizRoutes);
router.use('/users', userRoutes);
router.use('/notifications', notificationRoutes);
router.use('/upload', uploadRoutes);
export default router;
